name: GitHub Workflow Demo
# Whenever a push is detected on this repo 
on: [push]

# In file global variables
env: 
  GLOBAL_VAR: Hello, Welcome!
  PASSWORD: ${{ secrets.SECRETPW }}

# What do we want our workflow to do
jobs:
  # Name of job 
  actions_demo:
    # What type of virtual machine do we want it to run on 
    runs-on: ubuntu-latest
    env: 
      COLOUR: Gold
    steps: 
    - run: echo "Hello World"
    - run: ls
    - uses: actions/checkout@v3
    - run: ls
    - run: chmod +x Script1.sh
    - run: ./Script1.sh
    - run: echo $GLOBAL_VAR
    - run: echo $COLOUR
    - run: echo $PASSWORD
  
  second_job: 
    runs-on: ubuntu-latest
    steps: 
    - run: echo "Is this working"
    - uses: actions/checkout@v3
    - run: ls
    - run: chmod +x script2.sh
    - run: ./script2.sh
    - run: echo $COLOUR
