name: GitHub Workflow Demo

on: [push]

# What do we want our workflow to do
jobs:
  
  actions_demo:
    # What type of virtual machine do we want it to run on 
    runs-on: ubuntu-latest
    steps: 
    - run: echo "Hello GitHub"
    - run: touch test.txt
    - run: ls
    -uses: actions/checkout@v3
    -run: ls
    -run chmod+x script1.sh
    run: ./script1.sh 
