#Name of workflow
name: Github Workflow Demo

#Whenever push is detected on this repo, it will run this process
on: [push]

#What do we want our workflow to do: 
jobs:
#Name of Job
  actions_demo:
  #What type of VM do we want to run it on
  runs-on: ubuntu-latest
  steps:
  -run: echo "Hello World"
  -run: ls
